### ISSUE TITLE
usage

### ISSUE THREAD

**Issue by pizzav-xyz** [rockerle/LitematicaMapartBot#2]
how to use this?

**Comment by rockerle** [comment]
1.) Select a Schematic Placement you want to build in the Placements List of Litematica
2.) Check the Hotkey to start building. By default it's J but can be set in the vanilla keybinding menu. https://imgur.com/qZErDrP
3.) Set in the Litematic Configs->Info Overlays->verifierOverlayEnabled to false. Otherwise the placement will flash a lot on screen
4.) Get Inventory full with blocks for the mapart.
5.) Pray
6.) Press Hotkey to start building.

**Comment by pizzav-xyz** [comment]
> 1.) Select a Schematic Placement you want to build in the Placements List of Litematica
> 2.) Check the Hotkey to start building. By default it's J but can be set in the vanilla keybinding menu. https://imgur.com/qZErDrP
> 3.) Set in the Litematic Configs->Info Overlays->verifierOverlayEnabled to false. Otherwise the placement will flash a lot on screen
> 4.) Get Inventory full with blocks for the mapart.
> 5.) Pray
> 6.) Press Hotkey to start building.

Can you fix crash with pressing key before schematic loaded and how do I pause to restock

**Comment by rockerle** [comment]
Sorry, but I won't fix minor stuff that is just annoying while using it like crashing without selecting a schematic or a pause feature. I want the bot to build until it's running out of blocks or is done. When it doesn't have any blocks to place it will stop and you can restock.

If you really want a feature I'm open for pull requests (as long as I understand whats happening in the submitted code) :)

I also only tested it with completely flat or strictly staircased maparts. If you try to build one of the fancy variants that has floating blocks and staircases up and down, I don't know how the bot will work when it has a block that it can't reach.

**Comment by pizzav-xyz** [comment]
@rockerle how do I pause to restock

**Comment by rockerle** [comment]
> When it doesn't have any blocks to place it will stop and you can restock.

It pauses/stops on it's own when it can't place any blocks. Otherwise no pause.

**Comment by rockerle** [comment]
When I'm updating my bedrockminer to 1.20.5 I'll also add a message to show when no placement is selected instead of crashing ~~and I can add that the hotkey is a toggle so after toggeling off it will not continue to build~~.

**Comment by pizzav-xyz** [comment]
ok
